const express=require('express');
const cors=require('cors');
const path=require('path');
const ticketsRoutes=require('./routes/tickets');
const posRoutes=require('./routes/pos');
const backofficeRoutes=require('./routes/backoffice');
const barRoutes=require('./routes/bar');
const cardapioRoutes=require('./routes/cardapio');
const checkinRoutes=require('./routes/checkin');
const app=express();
const PORT=process.env.PORT||8000;
app.use(cors()); app.use(express.json());
app.use('/api',ticketsRoutes); app.use('/api',posRoutes); app.use('/api',backofficeRoutes); app.use('/api',barRoutes); app.use('/api',cardapioRoutes); app.use('/api',checkinRoutes);
app.use(express.static(path.join(__dirname,'..','public')));
app.listen(PORT,'0.0.0.0',()=>console.log(`Core Tickets rodando na porta ${PORT}`));
